[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
engine = { path = "../engine" }
winit = "0.30.8"
ultraviolet = "0.9.2"
rand = "0.8.5"
rand_distr = "0.4.3"
whoami = "1.5.2"
maplit = "1.0.2"
reqwest = { version = "0.12.15", features = ["blocking"] }
